// src/components/site/PostCard.tsx
import { motion } from "framer-motion";
import { ArrowUpRight } from "lucide-react";
import type { MockPost } from "@/lib/mock-data";
import { formatDate } from "@/lib/mock-data";

export function PostCard({ post, index = 0 }: { post: MockPost; index?: number }) {
  return (
    <motion.article
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25, delay: index * 0.04, ease: "easeOut" }}
      className="group relative rounded-xl border border-border bg-card/60 p-5 transition-colors hover:border-primary/40"
    >
      <div className="flex items-center justify-between font-mono text-[11px] uppercase tracking-widest text-muted-foreground">
        <span>{formatDate(post.publishedAt)}</span>
        <span>{post.readingTime}</span>
      </div>
      <h3 className="mt-2 text-lg font-semibold text-foreground transition-colors group-hover:text-primary">
        {post.title}
      </h3>
      <p className="mt-2 text-sm text-muted-foreground">{post.summary}</p>
      <div className="mt-4 flex items-center justify-between">
        <div className="flex flex-wrap gap-1.5">
          {post.tags.map((t) => (
            <span
              key={t}
              className="rounded border border-border bg-muted/40 px-1.5 py-0.5 font-mono text-[10px] text-muted-foreground"
            >
              #{t}
            </span>
          ))}
        </div>
        <ArrowUpRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-primary" />
      </div>
    </motion.article>
  );
}

// app/components/PostCard.vue
<script setup lang="ts">
const props = defineProps<{
  post: { path?: string; title?: string; description?: string; date?: string; tags?: string[]; minutes?: number }
}>()
const { t } = useLang()

const dateLabel = computed(() => {
  if (!props.post.date) return ''
  const d = new Date(props.post.date)
  return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日`
})
</script>

<template>
  <NuxtLink
    :to="post.path"
    class="card-sweep group block rounded-xl border border-border bg-surface p-5 sm:p-6 transition-all duration-300 hover:border-border-strong hover:bg-surface-hover hover:shadow-[var(--glow)] hover:-translate-y-0.5"
  >
    <div class="flex items-center gap-3 font-mono text-xs text-muted">
      <time>{{ dateLabel }}</time>
      <span class="text-border-strong">·</span>
      <span>{{ post.minutes }} {{ t.minutes }}</span>
    </div>
    <h3 class="mt-2.5 text-lg font-semibold leading-snug text-ink group-hover:text-accent transition-colors">
      {{ post.title }}
    </h3>
    <p class="mt-2 text-sm leading-relaxed text-ink-soft line-clamp-2">
      {{ post.description }}
    </p>
    <div v-if="post.tags?.length" class="mt-3.5 flex flex-wrap gap-2">
      <span v-for="tag in post.tags" :key="tag" class="font-mono text-[11px] text-muted group-hover:text-ink-soft transition-colors">
        <span class="text-accent/70">#</span>{{ tag }}
      </span>
    </div>
  </NuxtLink>
</template>
